### ISSUE TITLE
suggestion: shorten examples/link to

### ISSUE THREAD

**Issue by bkardell** [pcafstockf/PokerFace#1]
You have some places where you link to code which is dead simple, but includes pages of documentation.  For example:

https://raw.githubusercontent.com/pcafstockf/PokerFace/master/Samples/ScriptRoot/EndpointTemplate.js

It might be better to show the simplicity and link to the fully annotated documentation version

**Comment by pcafstockf** [comment]
Thanks for the feedback.  It helped me see that I was documenting the code instead of how to use it.

I think the [site](http://pcafstockf.github.io/PokerFace/index.html) is now more of a user guide.
Let me know what you think.
