### ISSUE TITLE
Proxy for videos

### ISSUE THREAD

**Issue by sezertt** [pcafstockf/PokerFace#3]
Hi, I am trying to use your project for a simple video connection. I am trying to get the videos through one port and using your config like this 
```
<server cpu="0.66" soTimeout="0">
	<listen address="0.0.0.0" port="15000" />
</server>
<targets connectTimeout="30000" bufferSize="1024" >
	<target pattern="/30001" url="http://x.x.x.x:30001" />
        ...
</targets>
```
But as the connections come and go, my direct buffer memory is increasing wildly and soon to be OOMe. Is there something that you can suggest? At first I noticed that buffer.reset(); gives invalidmark exception so took it into try catch block then I checked the trace of active buffers in pool and every connection/disconnection it increased.  TargetResponseConsumer almost never returns them. Also I noticed that after disconnection TargetResponseConsumer requests another buffer(getByteBuffer) which I don't understand why. 
That's all I can say for now, thank you.

**Comment by pcafstockf** [comment]
Hi, I recently did another project with Apache async and gained a much better understanding of that library (including it's buffering) and how it is meant to be used, than I had when I originally wrote PokerFace.
Thanks for your description, it is helpful.
I'll have some time over the Christmas holiday and will try to get this resolved then (I'm sorry I just don't have time to look into it right now).

**Comment by pcafstockf** [comment]
@sezertt I was able to reproduce this OOMe with the info you provided.  Multiple new ByteBuffer instances with every request.  Reworked that BufferIOController.getByteBuffer method and changed the reset() to a clear() (which was the original intent anyway).  ByteBuffer instances no longer accumulating even under heavy load.

You should be good to go with the v0.9.2 release.

Thanks for the report.
