### ISSUE TITLE
Interested in diving into this project

### ISSUE THREAD

**Issue by dev-ns8** [pcafstockf/PokerFace#4]
I am interested in diving into this open-source project a little bit and had a couple of questions for the author.  Couldn't find any contact info anywhere for said individual so I thought this would be the best place to try to get in touch.  If we could discuss a couple of points via email that would be fantastic

**Comment by pcafstockf** [comment]
Happy to discuss.  You can reach me using [pokerface@bytelightning.com](mailto:pokerface@bytelightning.com)

**Comment by pcafstockf** [comment]
Closing as stale.
